#
# image.yml
#
# Builds a multi-architecture (amd64 and arm64) image for this project
# and pushes it to Docker Hub.
#
name: build-image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-container:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 \
            --push \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/md-validator:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/md-validator:0.10 \
            .
